SOLVER_EXACT = "exact"
SOLVER_ALNS = "alns"

MODE_COST = "cost"
MODE_EMISSION = "emission"
MODE_WEIGHTED = "weighted"
MODE_EPSILON_COST = "epsilon_cost"

VALID_SOLVERS = {SOLVER_EXACT, SOLVER_ALNS}
VALID_OBJECTIVE_MODES = {
    MODE_COST, MODE_EMISSION, MODE_WEIGHTED, MODE_EPSILON_COST
}
